/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "filesystem.h"

int *
lectura_1_svc(variablesCompartidas *argp, struct svc_req *rqstp)
{
	static int  result;
	FILE *archivo;
	char * buffer;
	archivo = fopen(argp->nombreA,"r");
	// Con respecto al buffer, fijarse en el tamaño,se tiene que armar alguna estructura para que el argp->cantLeerA sea igual al tamaño del char *buffer....y ver la parte de trasmitir por partes para archivo grandes.
	printf("Nombre del archivo Lectura: %s\n",argp->nombreA );
	//printf("Buffer a escribir : %s\n",argp->bufferEscritura);	
	if(archivo == NULL){
		printf("El archivo solicitado no existe.\n");
	}else{
		printf("El archivo se abrio correctamente\n");
		// Lectura del archivo pepe
		buffer = (char *)calloc(argp->cantLeerA, sizeof(unsigned char));		
		fread(buffer,sizeof(unsigned char),argp->cantLeerA,archivo);
		printf("%s \n",buffer);
		
		//ACA ALGO ESTA MAL, TENEMOS QUE DEVOLVER LA CANTIDAD leida A PARTIR DEL "archivo"
		printf("Posicion del Archivo: %d\n", argp->posicionA);
		printf("Cantidad de Bytes a leer: %d\n",argp->cantLeerA);		
		fclose(archivo);
	}
	//Cosas a imprimir utiles
	result = 1;
	return &result;
}

int *
escritura_1_svc(variablesCompartidas *argp, struct svc_req *rqstp)
{
	static int  result;
	FILE *archivo;
	archivo = fopen(argp->nombreA,"a");
	if(archivo == NULL){
		printf("no existe el archivo\n");
	}else{
		printf("se abrio correctamente\n");
		//Escritura de algo
		fwrite(argp->bufferEscritura,sizeof(unsigned char),strnlen(argp->bufferEscritura,255),archivo);
		printf("%s \n",argp->bufferEscritura);
		fclose(archivo);
	}
	printf("Nombre del archivo Escritura o creado: %s\n",argp->nombreA );
	printf("Posicion del Archivo: %d\n", argp->posicionA);
	printf("Cantidad de Bytes a leer: %d\n",argp->cantLeerA);
  	printf("Buffer a escribir : %s\n",argp->bufferEscritura);
	result = 1;
	return &result;
}
