/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servidorCF.h"
int *
lectura_1_svc(variablesCompartidas *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Nombre del archivo: %s\n",(argp->nombreA));
	printf("Posicion del Archivo: %d\n", argp->posicionA);
	printf("Cantidad de Bytes a leer: %d\n",argp->cantLeerA);
	/*
		Ejecucion de la lectura de un archivo del servidor
	*/
	//printf("Buffer a escribir : %s\n",argp->bufferEcritura);
	result = 1;
	return &result;
}

int *
ecritura_1_svc(variablesCompartidas *argp, struct svc_req *rqstp)
{
	static int  result;

	result=1;
	return &result;
}