/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ej4.h"

bool_t
xdr_retornoValores (XDR *xdrs, retornoValores *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->ret_bytes, MAX_STRUCT,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cant_bytes))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->bytes_leidos))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lecturaParametros (XDR *xdrs, lecturaParametros *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->filename, MAX_FILE))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pos))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cant))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_escrituraParametros (XDR *xdrs, escrituraParametros *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->e, MAX_FILE))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->buffer, MAX_STRUCT))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cant))
		 return FALSE;
	return TRUE;
}
