/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ej4.h"

struct retornoValores *
lectura_1_svc(struct lecturaParametros *argp, struct svc_req *rqstp)
{
	static struct retornoValores  result; 	//filename, pos, cant
	FILE *archivo;
	//inicio de estructura
	result.bytes_leidos = 0;
//	result.ret_bytes= NULL;
	result.cant_bytes = argp->cant;

	archivo = fopen(argp->filename,"rb");
	// Con respecto al buffer, fijarse en el tamaño,se tiene que armar alguna estructura para que el argp->cantLeerA sea igual al tamaño 		char *buffer....y ver la parte de trasmitir por partes para archivo grandes.
	printf("Nombre del archivo a leer: %s\n",argp->filename);
	if(archivo == NULL){
		printf("El archivo solicitado no existe.\n");
	}else{
		printf("El archivo se abrio correctamente\n");
		//posicionamiento del puntero
		fseek(archivo,argp->pos, SEEK_SET); // ARCHIVO, POSICION, FORMATO DE SET
		printf("Posicion buscada en el archivo: %d\n",argp->pos);

		//lectura del archivo
		//result.ret_bytes = (char *)calloc(argp->cant, sizeof(unsigned char));
		result.bytes_leidos = fread(result.ret_bytes,sizeof(unsigned char),argp->cant,archivo);
/*		int resultado_posicion = ftell(archivo);
		resultado_posicion = resultado_posicion - argp->pos;
*/
		//result.ret_bytes = fgetc(archivo);
		printf("%d\n",result.bytes_leidos);
		//printf("Strlen(result) = %f\n", strlen(result.ret_bytes));
		//printf("Posicion final = %d\n",re);
		fclose(archivo);
		printf("*******************************************************************\n");
	}

	return &result;
}

int *
escritura_1_svc(struct escrituraParametros *argp, struct svc_req *rqstp)
{
	static int  result;
	FILE *archivo, *archivo_remoto;
	unsigned char c;
	archivo = fopen(argp->e,"rb");
	archivo_remoto = fopen("archivo_remoto","wb");
	if(archivo == NULL || archivo_remoto == NULL){

		printf("no existe el archivo\n");
		result = -1; // Dado que no existe el archivo, se retorna -1 para indicar un error

	}else{

		printf("Nombre del archivo Escritura o creado: %s\n",argp->e);
		//int pos_inicial = ftell(archivo);

		//Escritura de algo con salto de linea al final, sino la proxima escritura se hace a continuación
		fwrite(argp->buffer,sizeof(unsigned char),strnlen(argp->buffer,255),archivo);
		fwrite("\n",sizeof(unsigned char),1,archivo);
		//Copia en el archivo remoto
		//fwrite(argp->buffer,sizeof(unsigned char),strnlen(argp->buffer,255),archivo_remoto);
		//fwrite("\n",sizeof(unsigned char),1,archivo_remoto);
		fseek(archivo,0,SEEK_END); //ESTO VA el puntero al final del archivo
		int posicionFinal = ftell(archivo);
		fseek(archivo, 0,SEEK_SET); //VA AL PRINCIPIO
		int a = 0;
		while(a != posicionFinal )
		 		{
					c=fgetc(archivo);
					fputc(c,archivo_remoto);
					//printf("%d \n",c);
					a++;
		 		}
		printf("Copias con exito\n");
		printf("Lo que se copio al final del archivo:'%s'\n",argp->buffer);
		fclose(archivo);
		fclose(archivo_remoto);
		printf("*******************************************************************\n");
	}
	result = 1;
	return &result;

}
