/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "simp.h"
#define foo 127
#include <unistd.h>

void
simp_prog_1(char *host, int valX, int valY)
{
	CLIENT *clnt;
	int  *result_1;
	operands  add_1_arg;
	int  *result_2;
	operands  sub_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SIMP_PROG, SIMP_VERSION, "udp");	

	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	//lectura de los valores que vienen de parametro par la terminal.
  	add_1_arg.x=valX;
	add_1_arg.y=valY;
	// se realizan las cuentas segun los parametros que se tengan
	
	
	result_1 = add_1(&add_1_arg, clnt);
		
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else
	{
		printf("Resultado de la suma = %d",*result_1);
	}
	result_2 = sub_1(&sub_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("Resultado de la suma = %d",*result_2);
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	if (argc < 4) {
		printf ("usage: %s server_host ValorX ValorY\n", argv[0]);
		exit (1);
	}
	host = argv[1];	
	// SUponiendo que todo funciona, colocando algun sleep o exit no estaria sucediendo nada.
	simp_prog_1 (host, atoi(argv[2]), atoi(argv[3]));
	
exit (0);
}
