/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "simp.h"
#define foo 127


int *
add_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int result;
	printf("add(%d,%d) suma de valores \n",argp->x, argp->y);
	result= argp->x + argp->y ;
	return &result;
}

int *
sub_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;
	return &result;
}
