/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ejercicio5.h"
#include "time.h"

void
servidorcf_prog_1(char *host)
{
	CLIENT *clnt;
	double  *result_1;
	char *tiempo_1_arg;
	clock_t t_ini,t_fin;
	t_ini = clock();
	double seg;
#ifndef	DEBUG
	clnt = clnt_create (host, SERVIDORCF_PROG, SIMP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = tiempo_1((void*)&tiempo_1_arg, clnt);
	t_fin = clock();
	seg = (double)(t_fin - t_ini) * 1000/ CLOCKS_PER_SEC;	
	printf("%f \n",seg);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	servidorcf_prog_1 (host);
exit (0);
}
