/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EJERCICIO5_H_RPCGEN
#define _EJERCICIO5_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SERVIDORCF_PROG 0x40000001
#define SIMP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define TIEMPO 1
extern  double * tiempo_1(void *, CLIENT *);
extern  double * tiempo_1_svc(void *, struct svc_req *);
extern int servidorcf_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TIEMPO 1
extern  double * tiempo_1();
extern  double * tiempo_1_svc();
extern int servidorcf_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EJERCICIO5_H_RPCGEN */
