/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ejercicio5.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>

int 

double *
tiempo_1_svc(void *argp, struct svc_req *rqstp)
{
	static double  result;
	sleep(2); // es simplemente para entender lo que sucede
	result = 1;
	return &result;
}
