/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUPERADORTIEMPO_H_RPCGEN
#define _SUPERADORTIEMPO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct variablesTiempo {
	int tiempo;
};
typedef struct variablesTiempo variablesTiempo;

#define SERVIDORCF_PROG 0x30000001
#define SIMP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define TIEMPO 1
extern  double * tiempo_1(variablesTiempo *, CLIENT *);
extern  double * tiempo_1_svc(variablesTiempo *, struct svc_req *);
extern int servidorcf_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TIEMPO 1
extern  double * tiempo_1();
extern  double * tiempo_1_svc();
extern int servidorcf_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_variablesTiempo (XDR *, variablesTiempo*);

#else /* K&R C */
extern bool_t xdr_variablesTiempo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUPERADORTIEMPO_H_RPCGEN */
