/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "superadorTiempo.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>

void
servidorcf_prog_1(char *host)
{
	CLIENT *clnt;
	double  *result_1;
	char *tiempo_1_arg;

	clock_t t_ini;
	double seg;
	//gettimeofday(&t_ini, NULL);
	
	t_ini = clock();
#ifndef	DEBUG
	clnt = clnt_create (host, SERVIDORCF_PROG, SIMP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = tiempo_1((void*)&tiempo_1_arg, clnt);
	printf("Resultado servidfor:%f \n",*result_1);	
	seg = (double) t_ini/100000;
	printf("Resultadop de inicio cliente: %f\n",seg);
	printf("CLOCKS_PER_SEC = %ld\n",CLOCKS_PER_SEC);
	seg = (*result_1 - seg); 
	printf("Resultado final: %lf \n",seg);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	servidorcf_prog_1 (host);
exit (0);
}
