/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "superadorTiempo.h"

bool_t
xdr_variablesTiempo (XDR *xdrs, variablesTiempo *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->tiempo))
		 return FALSE;
	return TRUE;
}
