/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "superadorTiempo.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>

double tiempoEspera =0;

double *
tiempo_1_svc(void *argp, struct svc_req *rqstp)
{
	static double  result;
	tiempoEspera = tiempoEspera + 2;
	printf("El tiempo de espera en servidor: %f\n",tiempoEspera);
	sleep(tiempoEspera);
	result=tiempoEspera;
	return &result;
}
