/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EJ4_H_RPCGEN
#define _EJ4_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_STRUCT 255
#define MAX_FILE 100

struct retornoValores {
	u_char ret_bytes[MAX_STRUCT];
	int cant_bytes;
	int bytes_leidos;
};
typedef struct retornoValores retornoValores;

struct lecturaParametros {
	char *filename;
	int pos;
	int cant;
};
typedef struct lecturaParametros lecturaParametros;

struct escrituraParametros {
	char *e;
	char *buffer;
	int cant;
};
typedef struct escrituraParametros escrituraParametros;

#define filesystem_prg 0x30000001
#define filesystem_ver 1

#if defined(__STDC__) || defined(__cplusplus)
#define LECTURA 1
extern  struct retornoValores * lectura_1(struct lecturaParametros *, CLIENT *);
extern  struct retornoValores * lectura_1_svc(struct lecturaParametros *, struct svc_req *);
#define ESCRITURA 2
extern  int * escritura_1(struct escrituraParametros *, CLIENT *);
extern  int * escritura_1_svc(struct escrituraParametros *, struct svc_req *);
extern int filesystem_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LECTURA 1
extern  struct retornoValores * lectura_1();
extern  struct retornoValores * lectura_1_svc();
#define ESCRITURA 2
extern  int * escritura_1();
extern  int * escritura_1_svc();
extern int filesystem_prg_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_retornoValores (XDR *, retornoValores*);
extern  bool_t xdr_lecturaParametros (XDR *, lecturaParametros*);
extern  bool_t xdr_escrituraParametros (XDR *, escrituraParametros*);

#else /* K&R C */
extern bool_t xdr_retornoValores ();
extern bool_t xdr_lecturaParametros ();
extern bool_t xdr_escrituraParametros ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EJ4_H_RPCGEN */
