/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "simp.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>

int *
add_1_svc(operands *argp, struct svc_req *rqstp)
{
	
	static int  result;	
	sleep(90);
	result = 1;
	//exit(1); // conexion UDP/TCP prueba servidor result = 1;
	return &result;
	
}

int *
sub_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;
	result=1;
	return &result;
}
