/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "filesystemv2.h"


void
servidorcf_prog_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	variablesLectura  lectura_1_arg;
	int  *result_2;
	variablesEscritura  escritura_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SERVIDORCF_PROG, SIMP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	/*lectura_1_arg.nombreA = "pruebaTexto.txt";
	lectura_1_arg.posicionA = 0;
	lectura_1_arg.cantLeerA = 255;
	result_1 = lectura_1(&lectura_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else printf("Buffer devuelto: %s\n",*result_1);
*/
	escritura_1_arg.nombreA = "pruebaTexto.txt";
	escritura_1_arg.cantBytes = 0;
	escritura_1_arg.bufferEscritura = "Y yo soy José Luis";
	result_2 = escritura_1(&escritura_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else printf ("Resultado devuelto: %d", *result_2);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	servidorcf_prog_1 (host);
exit (0);
}
