/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "userlookup.h"

int *
byname_1_svc(username *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

username *
bynum_1_svc(int *argp, struct svc_req *rqstp)
{
	static username  result;

	/*
	 * insert server code here
	 */

	return &result;
}
