/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "superadorTiempo.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>


void
servidorcf_prog_1(char *host,int valorTiempo)
{
	CLIENT *clnt;
	double  *result_1;
	variablesTiempo  tiempo_1_arg;
	clock_t t_ini;
	double seg;
	
	#ifndef	DEBUG
	clnt = clnt_create (host, SERVIDORCF_PROG, SIMP_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	// argumento de tiempo
	t_ini = clock();
	tiempo_1_arg.tiempo = valorTiempo;
	seg = ((double)t_ini)/1000000;
	printf("Resultado de inicio cliente: %f\n",seg);

	//traemos el resultado desde el servidor	
	result_1 = tiempo_1((void*)&tiempo_1_arg, clnt);	
	printf("Resultado servidor:%f\n",*result_1);
	
	// informacion util
	seg = (*result_1) - seg;
	printf("Resultado final: %f\n",seg);
	
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{

	char *host;
	if (argc < 3) {
		printf ("usage: %s server_host tiempo_Espera \n", argv[0]);
		exit (1);
	}
	host = argv[1];
	servidorcf_prog_1((host),atoi(argv[2]));

	exit (0);
}
